<main class="container-register">
    <h1>Connexion</h1>
    <form action="connection.php" method="POST">
        <labeL>Email
        <div>
            <input type="text" name="email" required />
        </div>
        </labeL>
        
        <labeL>Mot de passe 
        <div>
            <input type="password" name="password" required />
        </div>
        </labeL>
        
        <p>Heureux de vous revoir.</p>
        
        <input type="submit" value="Connexion"/>
    </form>
</main>